<br>
<br>

### (Official) Installation guide @ https://pytorch.org/get-started/locally/

In [ ]:
!pip install torch==1.10.2
!pip install torchvision==0.11.3
!pip install torchaudio==0.10.2

# "액세스가 거부되었습니다" 에러가 발생하거나 정상적으로 설치가 진행되지 않을 경우,
# cmd(명령프롬프트) 우클릭 & 관리자권한으로 실행 후,
# 느낌표를 제외한 명령어를 1줄씩 입력 & 실행하여 설치를 진행합니다.

In [6]:
import torch, torchvision, torchaudio

print(torch.__version__)
print(torchvision.__version__)
print(torchaudio.__version__)

1.10.2
0.11.3
0.10.2


<br>
<br>

# 1. Tensors
<br>

- (Official) **torch.Tensor** @ https://pytorch.org/docs/stable/tensors.html

<br>
<br>

### 1) **Scalar** == a single number == a zero dimension tensor

<br>

#### \+ ndim / shape / dtype / device
#### \+ item() / type()

In [ ]:
scalar = torch.tensor(3)

scalar

tensor(3)

In [ ]:
scalar.ndim # 0차원

0

In [ ]:
scalar.shape # == np.ndarray.shape

torch.Size([])

In [ ]:
scalar.dtype

torch.int64

In [ ]:
scalar.device

device(type='cpu')

In [ ]:
scalar.item() # only works with one-element tensors

3

In [ ]:
# Type-casting

scalar.type(torch.float16).item()

3.0

<br>
<br>

### 2) **vector** == an array == a single dimension tensor

In [ ]:
vector = torch.tensor([1, 2, 3])

vector

tensor([1, 2, 3])

In [ ]:
vector.ndim # 1차원 벡터

1

In [ ]:
vector.shape # == np.ndarray.shape

torch.Size([3])

In [ ]:
vector.item()

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
vector[2].item()

3

<br>
<br>

### 3) **matrix** == a multiple dimension tensor

In [ ]:
matrix = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
matrix.ndim # 2차원 행렬

2

In [ ]:
matrix.shape # == np.ndarray.shape

torch.Size([2, 3])

In [ ]:
matrix[1, 2].item() # indexing 

6

<br>
<br>

### 4) random / zeros / ones / arange

In [ ]:
random_tensor = torch.rand(size=(2, 3))

random_tensor

tensor([[0.0800, 0.0486, 0.4888],
        [0.0733, 0.4079, 0.4889]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.0010, 0.3740, 0.0352],
        [0.0830, 0.2422, 0.5024]], dtype=torch.float16)

In [ ]:
random_tensor.dtype

torch.float16

In [ ]:
random_tensor.shape # == np.ndarray.shape

torch.Size([2, 3])

In [ ]:
zeros = torch.zeros(size=(2, 3))

zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(2, 3))

ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
arange = torch.arange(3, 15, 2)

arange

tensor([ 3,  5,  7,  9, 11, 13])

In [ ]:
zeros_like = torch.zeros_like(arange)

zeros_like

tensor([0, 0, 0, 0, 0, 0])

<br>
<br>

# 2. Tensor operations


<br>
<br>

### Descriptive stats / argmax / matrix calculation / reshape

In [ ]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.9883, 0.6587, 0.0312],
        [0.8950, 0.8906, 0.6279]], dtype=torch.float16)

In [ ]:
print(random_tensor.min().item())
print(random_tensor.max().item())
print(random_tensor.mean().item())
print(random_tensor.std().item())
print(random_tensor.sum().item())

0.03125
0.98828125
0.68212890625
0.34912109375
4.09375


In [ ]:
print(torch.min(random_tensor).item())
print(torch.max(random_tensor).item())
print(torch.mean(random_tensor).item())
print(torch.std(random_tensor).item())
print(torch.sum(random_tensor).item())

0.03125
0.98828125
0.68212890625
0.34912109375
4.09375


In [ ]:
random_tensor

tensor([[0.9883, 0.6587, 0.0312],
        [0.8950, 0.8906, 0.6279]], dtype=torch.float16)

In [ ]:
random_tensor.argmax(dim=0) # 열 방향

tensor([0, 1, 1])

In [ ]:
random_tensor.argmax(dim=1) # 행 방향

tensor([0, 0])

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor

tensor([1, 2, 3])

In [ ]:
tensor + 10 # numpy-like

tensor([11, 12, 13])

In [ ]:
tensor * 10 # numpy-like

tensor([10, 20, 30])

In [ ]:
print(tensor * 10)
print(torch.mul(tensor, 10))
print(torch.multiply(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([10, 20, 30])


In [ ]:
# Matrix multiplication @ https://www.mathsisfun.com/algebra/matrix-multiplying.html

tensor = torch.tensor([[1, 2], [3, 4]])

tensor

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor.T # Transpose

tensor([[1, 3],
        [2, 4]])

In [ ]:
tensor * tensor # Element-wise multiplication

tensor([[ 1,  4],
        [ 9, 16]])

In [ ]:
# Matrix multiplication 1 

torch.matmul(tensor, tensor) 

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
# Matrix multiplication 2

torch.mm(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
# Matrix multiplication 3

tensor @ tensor 

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
tensor = torch.tensor([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
# tensor = torch.arange(1, 13).reshape(2, 6)

tensor

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [ ]:
tensor.reshape(3, 4) # numpy-like

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

<br>
<br>

# 3. Pytorch tensor <-> Numpy array


<br>
<br>

### 1) Pytorch tensor -> Numpy array 
<br>

#### -> tensor.**numpy**() 활용

In [ ]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[1.7578e-01, 2.2510e-01, 7.5000e-01],
        [2.2607e-01, 4.8828e-04, 2.6074e-01]], dtype=torch.float16)

In [ ]:
np_array = random_tensor.numpy()

np_array 

array([[1.758e-01, 2.251e-01, 7.500e-01],
       [2.261e-01, 4.883e-04, 2.607e-01]], dtype=float16)

In [ ]:
type(np_array)

numpy.ndarray

<br>
<br>

### 2) Numpy array -> Pytorch tensor
<br>

#### -> torch.**from_numpy**() 활용

In [ ]:
import numpy as np

In [ ]:
array = np.arange(12.0).reshape(2, 6)

array

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [ ]:
torch_tensor = torch.from_numpy(array)

torch_tensor

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]], dtype=torch.float64)

In [ ]:
type(torch_tensor)

torch.Tensor

<br>
<br>

# (Appendix 1) Reproducibility 


In [3]:
seed = 42 

torch.manual_seed(seed=seed) 

# torch.cuda.manual_seed(seed=seed) # for GPU 

In [ ]:
torch.manual_seed(seed=seed) 

random_tensor_1 = torch.rand(3, 4)

random_tensor_1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
# rand() 함수 호출 시마다 seed 값을 다시금 세팅해주어야 합니다. (아래 라인 주석 처리 시 다른 tensor가 만들어짐)
torch.manual_seed(seed=seed) 

random_tensor_2 = torch.rand(3, 4)

random_tensor_2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

<br>
<br>

# (Appendix 2) Using GPUs
<br>

### Colab (GPU로 런타임 변경 필요) 혹은 Nvidia GPU가 있는 로컬환경에서 실행해주세요. 
#### (PyTorch installation guide @ https://pytorch.org/get-started/locally/)

In [4]:
!nvidia-smi

Tue Nov 15 05:19:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch

In [5]:
# Check the availability of Nvidia GPU & CUDA (Nvidia GPUs' computing toolkit)

torch.cuda.is_available()

True

In [6]:
# Check the number of GPUs

torch.cuda.device_count()

1

In [7]:
# Set the variable "device" with "cuda" or "cpu"

device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

<br>
<br>

### Putting tensors (and models) on the GPU 
<br>

#### -> tensor.**to(device)** 활용

In [9]:
tensor = torch.tensor([1, 2, 3])

print(tensor)
print(tensor.device)

tensor([1, 2, 3])
cpu


In [10]:
tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
# tensor # To overwrite tensors, we should reassign them.

In [13]:
# GPU에 올라간 Tensor는 Numpy array로 변환 불가 (CPU로 되돌려야 함)

tensor_on_gpu.numpy()

TypeError: ignored

In [14]:
tensor_on_cpu = tensor_on_gpu.cpu() # returns a copy of the GPU tensor in CPU memory (the original tensor)

tensor_on_cpu.numpy()

array([1, 2, 3])