<br>
<br>

### (Official) Installation guide @ https://pytorch.org/get-started/locally/

In [2]:
!pip install torch==1.10.2
!pip install torchvision==0.11.3
!pip install torchaudio==0.10.2

# "액세스가 거부되었습니다" 에러가 발생하거나 정상적으로 설치가 진행되지 않을 경우,
# cmd(명령프롬프트) 우클릭 & 관리자권한으로 실행 후,
# 느낌표를 제외한 명령어를 1줄씩 입력 & 실행하여 설치를 진행합니다.

ERROR: Could not find a version that satisfies the requirement torch==1.10.2 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torch==1.10.2
ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3
ERROR: Could not find a version that satisfies the requirement torchvision==0.11.3 (from versions: 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0)
ERROR: No matching distribution found for torchvision==0.11.3
ERROR: Could not find a version that satisfies the requirement torchaudio==0.10.2 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torchaudio==0.10.2


In [1]:
import torch, torchvision, torchaudio

print(torch.__version__)
print(torchvision.__version__)
print(torchaudio.__version__)

2.4.0
0.19.0
2.4.0


<br>
<br>

# 1. Tensors
<br>

- (Official) **torch.Tensor** @ https://pytorch.org/docs/stable/tensors.html

In [3]:
import torch

<br>
<br>

### 1) **Scalar** == a single number == a zero dimension tensor

<br>

#### \+ ndim / shape / dtype / device
#### \+ item() / type()

In [16]:
scalar = torch.tensor(3) # tensor 자료형 변수 만들기

scalar

tensor(3)

In [17]:
scalar.ndim # 차원 갯수 체크 (Number of Dimension)

0

In [18]:
scalar.shape # 각 차원별 데이터 수 체크 (== np.ndarray.shape)

torch.Size([])

In [19]:
scalar.dtype
 # 데이터 타입 체크 

torch.int64

In [9]:
scalar.device # tensor 변수가 현재 할당된 장치(device) 체크

device(type='cpu')

In [20]:
scalar.item() # tensor 변수 내부의 값(item) 꺼내기 <- only works with one-element tensors

3

In [21]:
# Type-casting

scalar.type(torch.float16).item() # 자료형 변환 (type 함수 활용)

3.0

<br>
<br>

### 2) **vector** == an array == a single dimension tensor

In [13]:
vector = torch.tensor([1, 2, 3])

vector

tensor([1, 2, 3])

In [22]:
vector.ndim # 1차원 벡터

1

In [23]:
vector.shape # == np.ndarray.shape

torch.Size([3])

In [26]:
vector[1].item()

2

In [28]:
vector[2].item() # index 번호로 scalar tensor 꺼낸 후 값(item) 꺼내기

3

<br>
<br>

### 3) **matrix** == a multiple dimension tensor

In [29]:
matrix = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
matrix.ndim # 2차원 행렬

2

In [31]:
matrix.shape # == np.ndarray.shape

torch.Size([2, 3])

In [32]:
matrix.item()

RuntimeError: a Tensor with 6 elements cannot be converted to Scalar

In [33]:
matrix[1, 2].item() # indexing 

6

<br>
<br>

### 4) random / zeros / ones / arange

In [35]:
random_tensor = torch.randn(size=(2, 3)) # 랜덤 값들로 채워진 텐서 생성

random_tensor

tensor([[-0.9006,  0.1075, -0.0382],
        [ 0.8608, -0.6521, -1.5461]])

In [36]:
random_tensor.dtype

torch.float32

In [37]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.0312, 0.2153, 0.3467],
        [0.7427, 0.2871, 0.1577]], dtype=torch.float16)

In [38]:
random_tensor.dtype

torch.float16

In [39]:
random_tensor.shape # 각 차원별 데이터 수 체크 (== np.ndarray.shape)

torch.Size([2, 3])

In [40]:
zeros = torch.zeros(size=(2, 3))

zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [41]:
ones = torch.ones(size=(2, 3))

ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [43]:
arange = torch.arange(10) # array of range

arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
zeros_like = torch.zeros_like(arange)

zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<br>
<br>

# 2. Tensor operations


<br>
<br>

### Descriptive stats / argmax / matrix calculation / reshape

In [45]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.1128, 0.7456, 0.0176],
        [0.6157, 0.0117, 0.3027]], dtype=torch.float16)

In [46]:
print(random_tensor.min().item()) # 최소
print(random_tensor.max().item()) # 최대
print(random_tensor.mean().item()) # 평균
print(random_tensor.std().item()) # 표준편차
print(random_tensor.sum().item()) # 합계

0.01171875
0.74560546875
0.301025390625
0.31494140625
1.806640625


In [47]:
print(torch.min(random_tensor).item()) # 최소
print(torch.max(random_tensor).item()) # 최대
print(torch.mean(random_tensor).item()) # 평균
print(torch.std(random_tensor).item()) # 표준편차
print(torch.sum(random_tensor).item()) # 합계

0.01171875
0.74560546875
0.301025390625
0.31494140625
1.806640625


In [48]:
random_tensor

tensor([[0.1128, 0.7456, 0.0176],
        [0.6157, 0.0117, 0.3027]], dtype=torch.float16)

In [49]:
random_tensor.argmax(dim=0) # 열 방향으로 가장 큰 값들의 index 번호 확인하기

tensor([1, 0, 1])

In [50]:
random_tensor.argmax(dim=1) # 행 방향으로 가장 큰 값들의 index 번호 확인하기

tensor([1, 0])

In [51]:
tensor = torch.tensor([1, 2, 3])

tensor

tensor([1, 2, 3])

In [52]:
tensor + 10 # numpy-like

tensor([11, 12, 13])

In [53]:
tensor * 10 # numpy-like

tensor([10, 20, 30])

In [54]:
print(tensor * 10)
print(torch.mul(tensor, 10))
print(torch.multiply(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([10, 20, 30])


In [55]:
# Matrix multiplication @ https://www.mathsisfun.com/algebra/matrix-multiplying.html

tensor = torch.tensor([[1, 2], [3, 4]])

tensor

tensor([[1, 2],
        [3, 4]])

In [56]:
tensor.T # Transpose

tensor([[1, 3],
        [2, 4]])

In [57]:
tensor * tensor # Element-wise multiplication

tensor([[ 1,  4],
        [ 9, 16]])

In [58]:
# Matrix multiplication 1 

torch.matmul(tensor, tensor) # Matrix multiplication

tensor([[ 7, 10],
        [15, 22]])

In [59]:
# Matrix multiplication 2

torch.mm(tensor, tensor) # "M"atrix "m"ultiplication

tensor([[ 7, 10],
        [15, 22]])

In [60]:
# Matrix multiplication 3

tensor @ tensor # 행렬곱 연산자 @

tensor([[ 7, 10],
        [15, 22]])

In [61]:
tensor = torch.tensor([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
# tensor = torch.arange(1, 13).reshape(2, 6)

tensor

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [62]:
tensor.reshape(3, 4) # 모양(shape) 다시 바꾸기 (numpy-like)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

<br>
<br>

# 3. Pytorch tensor <-> Numpy array


<br>
<br>

### 1) Pytorch tensor -> Numpy array 
<br>

#### -> tensor.**numpy**() 활용

In [63]:
random_tensor = torch.rand(size=(2, 3), dtype=torch.float16)

random_tensor

tensor([[0.1245, 0.2666, 0.1250],
        [0.5625, 0.2544, 0.3271]], dtype=torch.float16)

In [64]:
np_array = random_tensor.numpy() # tensor 변수를 "numpy"로

np_array 

array([[0.1245, 0.2666, 0.125 ],
       [0.5625, 0.2544, 0.3271]], dtype=float16)

In [65]:
type(np_array)

numpy.ndarray

<br>
<br>

### 2) Numpy array -> Pytorch tensor
<br>

#### -> torch.**from_numpy**() 활용

In [66]:
import numpy as np

In [67]:
array = np.arange(12.0).reshape(2, 6)

array

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [68]:
torch_tensor = torch.from_numpy(array) # "numpy 변수로부터"

torch_tensor

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]], dtype=torch.float64)

In [69]:
type(torch_tensor)

torch.Tensor

<br>
<br>

# (Appendix 1) Reproducibility 


In [70]:
seed = 42 

torch.manual_seed(seed=seed) 

# torch.cuda.manual_seed(seed=seed) # for GPU 

In [71]:
torch.manual_seed(seed=seed) 

random_tensor_1 = torch.rand(3, 4)

random_tensor_1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [72]:
# rand() 함수 호출 시마다 seed 값을 다시금 세팅해주어야 합니다. (아래 라인 주석 처리 시 다른 tensor가 만들어짐)
torch.manual_seed(seed=seed) # 주석 처리 후 다시 실행해 테스트

random_tensor_2 = torch.rand(3, 4)

random_tensor_2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

<br>
<br>

# (Appendix 2) Using GPUs
<br>

### Colab (GPU로 런타임 변경 필요) 혹은 Nvidia GPU가 있는 로컬환경에서 실행해주세요. 
#### (PyTorch installation guide @ https://pytorch.org/get-started/locally/)

In [76]:
!nvidia-smi

NameError: name 'nvidia' is not defined

In [77]:
import torch

In [78]:
# Check the availability of Nvidia GPU & CUDA (Nvidia GPUs' computing toolkit)

torch.cuda.is_available() # cuda가 사용 가능한 지 체크 (is available?)

False

In [79]:
# Check the number of GPUs

torch.cuda.device_count()

0

In [80]:
# Set the variable "device" with "cuda" or "cpu"

device = "cuda" if torch.cuda.is_available() else "cpu" # cuda가 사용 가능한 지 체크 (is available?)

device

'cpu'

<br>
<br>

### Putting tensors (and models) on the GPU 
<br>

#### -> tensor.**to(device)** 활용

In [81]:
tensor = torch.tensor([1, 2, 3])

print(tensor)
print(tensor.device)

tensor([1, 2, 3])
cpu


In [84]:
tensor_on_gpu = tensor.to(device) # 특정한 device"로" 이동

tensor_on_gpu

tensor([1, 2, 3])

In [12]:
# tensor # To overwrite tensors, we should reassign them.

In [88]:
# GPU에 올라간 Tensor는 Numpy array로 변환 불가 (CPU로 되돌려야 함)

tensor_on_gpu.numpy() # tensor 변수를 "numpy" 변수로

array([1, 2, 3])

In [89]:
tensor_on_cpu = tensor_on_gpu.cpu() # returns a copy of the GPU tensor in CPU memory (the original tensor)

tensor_on_cpu.numpy() # tensor 변수를 "numpy" 변수로

array([1, 2, 3])